when@test: &sylius_uploader_test
    services:
        Sylius\Component\Core\Generator\ImagePathGeneratorInterface:
            class: Sylius\Behat\Service\Generator\UploadedImagePathGenerator

when@test_cached: *sylius_uploader_test
