sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch::switchAction

# see https://web.dev/change-password-url/
sylius_shop_request_password_reset_token_redirect:
    path: /.well-known/change-password
    methods: [GET]
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: sylius_shop_request_password_reset_token
        permanent: false

sylius_paypal:
    resource: "@SyliusPayPalPlugin/Resources/config/shop_routing.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
   

# Après avoir ajouté notre contrôleur PaymentRedirectController dans le container de service
# nous avons redéfini la route "sylius_shop_checkout_address" pour que le contrôleur qui soit 
# appelé soit le nôtre et non celui de Sylius (le contrôleur interne). 
# Ci-dessous, nous avons mentionné les méthodes de notre contrôleur (GET et PUT). 
     
sylius_shop_checkout_address:    
    path: /{_locale}/checkout/address     
    controller: App\Controller\PaymentRedirectController::redirectToMollie
    methods: [GET, PUT]  
    requirements:
        _locale: en_US|fr_FR
  
         
    